/*
 *  Copyright 2016-present Stephen Colebourne
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.joda.compare;

import java.time.LocalDate;

import org.immutables.value.Value;
import org.jspecify.annotations.Nullable;

/**
 * Sample bean generated using Immutables.
 */
@Value.Immutable
public interface ImmOrgPerson {
  // NOTES
  // Demonstrates the simplest usage
  // Requires setting up annotation processing
  // Processor generates source code
  // Lots of configuration options
  // Adding @Value.Parameter causes a static factory method to be generated
  // Instead of base.toBuilder(), the builder has a from(base) method
  // Withers are generated by default

  /**
   * Gets the name of the person.
   * @return the name
   */
  @Value.Parameter
  public abstract String getName();

  /**
   * Gets the date of birth.
   * @return the date of birth
   */
  @Value.Parameter
  public abstract @Nullable LocalDate getBirthDate();

}
